INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (21, 0.00, '推荐', '虽然猜到结果，但办公室现学现编也太牛了~~', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (22, 0.00, '力荐', 'Kint那句声泪俱下唱作俱佳的“fucking cops”真是让人五体投地。', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (23, 0.00, '力荐', '经典悬疑片， 一个几乎天衣无缝的谎言，一次精彩的瞒天过海。影片叙事非常成功，适当抖包袱的悬念自始至终紧紧捉住观众的注意力。谜底在最后一刻揭开，在瞠目结舌之余让人回味悠长。故事的寓意也发人深省：凶神恶煞的外表与大奸大恶之间并没有等号，也许狡猾谎言加上可怜的外表才是魔鬼的标准。这是一部百看不厌的影片，慢慢咀嚼对白和情节留下的隐蔽关子，精彩之处令人拍案叫绝。', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (24, 0.00, '推荐', 'IMDBTop250，其实真的是一个好结尾拯救了一个平庸的故事……', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (25, 0.00, '推荐', '小说家未必能干好诈骗犯，但诈骗犯肯定是个好小说家！', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (26, 0.00, '力荐', '“我不信仰上帝，但我敬畏上帝”', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (27, 0.00, '推荐', '全靠结尾点睛啊', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (28, 0.00, '推荐', '片名、主演再加上《惊声尖笑》的恶搞结局，以至于故事的结局很容易就能猜到。但是这并不代表这部电影不好看不好玩，只能说看不逢时。你永远也不要忽视掉那些看起来一无是处的人，他们一般都显得很弱小，很不显眼，但最终的那个人很可能就是他。★★★★', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (29, 0.00, '推荐', 'I dont believe in god, but im agraid of it.', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (30, 0.00, '推荐', '老派的虚实戏中戏手法。前半个小时云山雾罩，后面就慢慢开始有意思了。凯文·斯帕西这满嘴火车真是跑得太厉害了！！！', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (31, 0.00, '力荐', '我承认第一次没看明白，当时也对凯文·史派西不太熟，很多人物关系也没理清。不过看第二遍的时候就能很快理清头绪了，因为对演员也比较熟了，包括凯文、本尼西奥·德尔·托罗，还有演小林的就是《盗梦空间》中的老费舍。片子讲的就是凯文利用刚看到的几个词就编好一通完美的谎言把警察骗了，确实强大', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (32, 0.00, '推荐', '全片以倒叙的方式，给我们揭开了一桩借刀杀人惨案的真相。全片完全推翻了观众的惯性逻辑思维，将一个剧情复杂的故事拍得戏剧张力十足，自始至终扣人心弦。', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (33, 0.00, '力荐', '绝了，终于知道《无双》的结构和主线来自于哪里了。这么一看，无双只能说是个卑微的模仿者还没模仿到精髓。这部虽然前半部分唠叨琐碎，但是看完全片再回过头去，都是细节和伏笔啊我的天。以及凯文史派西的演技确实没话讲，fucking cops蕴含的情绪和潜台词复杂绵长，史派西掌握得十分恰当', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (34, 0.00, '还行', '结尾牛逼，只是悬念铺垫太晦涩、对白也絮絮叨叨，不好懂。Kevin Spacey都那么牛逼哄哄了，从一出场就能猜到结局。', 3);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (35, 0.00, '推荐', '一个天衣无缝的谎言 一次精彩的瞒天过海', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (36, 0.00, '力荐', '在看到最后一个镜头前还懵懵懂懂，觉得有很多细节串不起来。打算打三星半。结果那面墙一出来，我艹，屌爆了这编故事的能力和反应。五星推荐！', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (37, 0.00, '力荐', '哦 册那 骗到我了~~凯文史派西绝赞我越来越爱他了！！', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (38, 0.00, '力荐', '好看 不想错过电影任何一秒的感受', 5);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (39, 0.00, '推荐', '影片完全推翻了观众的惯性逻辑思维，将一个剧情复杂的故事拍得戏剧张力十足，自始至终扣人心弦。', 4);
INSERT INTO djangotest.movie_movieInfo (id, sentiment, start_title, short, score) VALUES (40, 0.00, '推荐', '满是算计的好剧本，“I am smarter than you”这句台词简直是影史超级大flag。最棒的镜头，莫过于最后史派西的跛脚变正常那段，太酷了！', 4);