# Generated by Django 3.0.8 on 2020-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='评分')),
                ('short', models.CharField(max_length=200, verbose_name='影评')),
                ('sentiment', models.FloatField(verbose_name='情感分析')),
                ('start_title', models.CharField(max_length=10, verbose_name='电影名称')),
            ],
        ),
    ]
