# Generated by Django 3.0.8 on 2020-08-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinfo',
            options={'managed': False},
        ),
    ]
